### ISSUE TITLE
Builder constant issue 

### ISSUE THREAD

**Issue by lolp1229** [HuskieRobotics/3061-lib#27]
im having a issue with the BuildConstants 

![1a9027dc06d5293e0f1bbd75f10d515e](https://user-images.githubusercontent.com/48162899/213879915-b46c6573-e413-4835-a87a-29a71b6c1451.png)

**Comment by gcschmit** [comment]
The BuildConstants file is generated when the project is built. The file won't exist until then. Run the "Build Robot Code" command and you should see it appear in the Robot folder.

**Comment by lolp1229** [comment]
It wouldnt let me build the code every time i try it says build failed after 1 actionable task : 1 executed

**Comment by gcschmit** [comment]
Would you share a link to your project in GitHub (or some other version control system)?

**Comment by martygubow** [comment]
I had a similar problem.  My build.gradle was not completing because I did not have the command line version of git in my path.  this is needed for the repositories   url = uri("https://maven.pkg.github.com/Mechanical-Advantage/AdvantageKit". 
Once Installed git the file was created, and the problem went away.

**Comment by gcschmit** [comment]
@lolp1229 If @martygubow's suggestion doesn't address your issue, please reopen. I've updated the README to state that git is an external dependency.

**Comment by lolp1229** [comment]
ive been trouble shooting for a few days and i still cant get it to work 
https://github.com/lolp1229/Main-code-2023-OKC heres the current code

**Comment by gcschmit** [comment]
Here's an update build.gradle file. If you want to use the automatically generated BuildConstants file, you need to include the gversion plugin and add the additional specifications at the bottom of the file. You also need to include the specify the dependency on AdvantageKit's annotation processor.

Rename this build.gradle
[build.gradle.txt](https://github.com/HuskieRobotics/3061-lib/files/10542559/build.gradle.txt)

**Comment by lolp1229** [comment]
thank you it works now
